// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartB.Data;

#nullable disable

namespace PartB.Data.Migrations
{
    [DbContext(typeof(GlossaryDBContext))]
    partial class GlossaryDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("PartB.Data.GlossaryTerm", b =>
                {
                    b.Property<string>("Term")
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Term");

                    b.ToTable("Glossary");

                    b.HasData(
                        new
                        {
                            Term = "abyssal plain",
                            Definition = "The ocean floor offshore from the continental margin, usually very flat with a slight slope."
                        },
                        new
                        {
                            Term = "accrete",
                            Definition = "v. To add terranes (small land masses or pieces of crust) to another, usually larger, land mass."
                        },
                        new
                        {
                            Term = "alkaline",
                            Definition = "Term pertaining to a highly basic, as opposed to acidic, subtance. For example,hydroxide or carbonate of sodium or potassium."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
